name: XEPB CD

on:
  push:
    branches:
      - main
  

jobs:
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    needs: [test]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
